### ISSUE TITLE
ربات دیگه کار نمیکنه

### ISSUE THREAD

**Issue by milaadd** [ehcaning/divar-telegram-bot#12]
این ارور رو میده
Started at 2024-09-14 16:31:32.787668.
Tokens length: 4487
2024-09-14 16:31:34.236943 - Got response: 200
Traceback (most recent call last):
  File "/storage/emulated/0/pol/forosh2ta3/forosh2ta3/mainf.py", line 144, in <module>
    data = get_data_page(page)
           ^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/pol/forosh2ta3/forosh2ta3/mainf.py", line 118, in get_data_page
    data = get_houses_list(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/pol/forosh2ta3/forosh2ta3/mainf.py", line 40, in get_houses_list
    return data["web_widgets"]["post_list"]
           ~~~~^^^^^^^^^^^^^^^
KeyError: 'web_widgets'


البته من از termux اندروید استفاده میکنم

**Comment by saeed74** [comment]
بله
متاسفانه دیوار فهمیده و api دیوار دیگه اطلاعات رو اینجوری نمیفرسته
و کلا پرونده رو بسته شده بدونید !

مثال:
`https://api.divar.ir/v8/web-search/mashhad/rent-residential?credit=60000000-80000000&rent=2000000-3000000
`
پاسخ api:

```
{
    "jli": {
        "category": {
            "value": "residential-rent"
        },
        "credit": {
            "max": 80000000,
            "min": 60000000
        },
        "rent": {
            "max": 3000000,
            "min": 2000000
        }
    },
    "multi_cities": [
        {
            "city_id": "3",
            "name": "مشهد",
            "parent_id": 880,
            "is_province": false
        }
    ]
}
```

همونطور که میبنید api هیچی توش نیست
